name: season_planer
description: "Plan your Season"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  appwrite: ^17.0.0
  sqflite: ^2.4.2
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2





flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/

