name: season_planner
description: "Plan your Season"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  appwrite: ^17.0.0
  sqflite: ^2.4.2
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  add_2_calendar_new: ^1.0.4
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.2


flutter_launcher_icons:
  image_path: "lib/assets/app_icon/app_icon.png"
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true


flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/splash_icon/splash_icon.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/

